/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RelatorioServicosExecutadosView.java
 *
 * Created on 02/11/2009, 14:49:39
 */

package br.com.prestadoradeservicos.views;

import br.com.prestadoradeservicos.controlers.RelatorioServicosExecutadosControler;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Anderson Luis Ribeiro
 */
public class RelatorioServicosExecutadosView extends javax.swing.JFrame {

    private MaskFormatter formatoData;
    private RelatorioServicosExecutadosControler controller;
    /** Creates new form RelatorioServicosExecutadosView */
    public RelatorioServicosExecutadosView(RelatorioServicosExecutadosControler controller) {
        initComponents();
        setLocationRelativeTo(null);
        this.controller = controller;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPeriodo = new javax.swing.JLabel();
        try{     formatoData = new MaskFormatter("##/##/####"); }catch(Exception erro){    JOptionPane.showMessageDialog(null, "Nao foi possivel setar a mascara: " + erro); }
        txtDataInicial = new JFormattedTextField(formatoData);
        try{     formatoData = new MaskFormatter("##/##/####"); }catch(Exception erro){    JOptionPane.showMessageDialog(null, "Nao foi possivel setar a mascara: " + erro); }
        txtDataFinal = new JFormattedTextField(formatoData);
        jbGerarRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Parâmetros do Relatório");

        lblPeriodo.setText("Data Inicial / Final:");

        jbGerarRelatorio.setText("Gerar");
        jbGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGerarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblPeriodo)
                .addGap(18, 18, 18)
                .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jbGerarRelatorio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeriodo)
                    .addComponent(txtDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGerarRelatorio))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGerarRelatorioActionPerformed
       controller.carregarRelatorio(formatarDataRelatorio(txtDataInicial.getText()), formatarDataRelatorio(txtDataFinal.getText()));
        
    }//GEN-LAST:event_jbGerarRelatorioActionPerformed

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RelatorioServicosExecutadosView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbGerarRelatorio;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JTextField txtDataFinal;
    private javax.swing.JTextField txtDataInicial;
    // End of variables declaration//GEN-END:variables

    private Date formatarDataRelatorio(String dataString){

        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        Date dataFormatada = null;
        try {
            dataFormatada = formatador.parse(dataString);
            return dataFormatada;
        } catch (ParseException ex) {
            Logger.getLogger(RelatorioServicosExecutadosView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return dataFormatada;

    }
}
